application:
  port: 8080
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "enhariharan@gmail.com"
  authorization_token: "paste-email-provider-auth-token-here"
  timeout_milliseconds: 10000
